# Generated by Django 2.1.7 on 2019-02-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_image',
            field=models.ImageField(help_text='用户上传眼底图', upload_to='diagnosis/images/', verbose_name='眼底图'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
